# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - if: ${{ failure() }}
        run: npm run test:diff
