# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - if: ${{ failure() }}
        run: npm run test:diff
