# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - if: ${{ failure() }}
        run: npm run test:diff
