# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Integration tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
      - if: ${{ failure() }}
        run: npm run test:diff
